spring: 
  profiles: 
    active:
    - dev
---
spring: 
  profiles: dev
  application: 
    name: springcloud-config-wk-dev
---
spring: 
  profiles: test
  application: 
    name: springcloud-config-wk-test
#保存utf-8格式