spring: 
  profiles: 
    active: 
    - dev
---
# 服务端口号
server:
  port: 7001
  
spring: 
  profiles: dev
  application: 
    name: springcloud-eureka-config

#Eureka 相关配置
eureka:
  client:
    #service-url:
      #defaultZone: http://eureka01.com:7001/eureka/
    # 是否从其他的服务中心同步服务列表
    fetch-registry: false
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: false
  instance: 
    hostname: eureka-server-7001
---
# 服务端口号
server:
  port: 7002
  
spring: 
  profiles: test
  application: 
    name: springcloud-eureka-config

#Eureka 相关配置
eureka:
  client:
    #service-url:
      #defaultZone: http://eureka01.com:7001/eureka/
    # 是否从其他的服务中心同步服务列表
    fetch-registry: false
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: false
  instance: 
    hostname: eureka-server-7002